export const Users = [
  {
    id: 1,
    profilePicture: "assets/001.jpg",
    username: "Lena Fischer",
  },
  {
    id: 2,
    profilePicture: "assets/002.jpg",
    username: "Tobias Meier",
  },
  {
    id: 3,
    profilePicture: "assets/003.jpg",
    username: "Emily Wagner",
  },
  {
    id: 4,
    profilePicture: "assets/001.jpg",
    username: "Jonas Becker",
  },
  {
    id: 5,
    profilePicture: "assets/002.jpg",
    username: "Mila Schulz",
  },
  {
    id: 6,
    profilePicture: "assets/003.jpg",
    username: "Noah Hoffmann",
  },
  {
    id: 7,
    profilePicture: "assets/003.jpg",
    username: "Sophie Braun",
  },
  {
    id: 8,
    profilePicture: "assets/002.jpg",
    username: "Leon Schäfer",
  },
  {
    id: 9,
    profilePicture: "assets/001.jpg",
    username: "Lara Zimmermann",
  },
  {
    id: 10,
    profilePicture: "assets/001.jpg",
    username: "Finn Kaiser",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/alex-robertson-33LI6oorkrY-unsplash.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/jessica-christian-s33JGIxpBjk-unsplash.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/pierre-lemos-wfOdYsDrxvs-unsplash.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/pierre-lemos-wfOdYsDrxvs-unsplash.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/jessica-christian-s33JGIxpBjk-unsplash.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/alex-robertson-33LI6oorkrY-unsplash.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/jessica-christian-s33JGIxpBjk-unsplash.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/alex-robertson-33LI6oorkrY-unsplash.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/alex-robertson-33LI6oorkrY-unsplash.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/jessica-christian-s33JGIxpBjk-unsplash.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
