export const Users = [
  {
    id: 1,
    profilePicture: "assets/001.jpg",
    username: "Lena Fischer",
    petType: "Dog",
    Friends: [
      { id: 2, username: "Tobias Meier", profilePicture: "assets/002.jpg" },
      { id: 3, username: "Emily Wagner", profilePicture: "assets/003.jpg" },
      { id: 4, username: "Jonas Becker", profilePicture: "assets/001.jpg" },
    ],
  },
  {
    id: 2,
    profilePicture: "assets/002.jpg",
    username: "Tobias Meier",
    petType: "Cat",
    Friends: [
      { id: 1, username: "Lena Fischer", profilePicture: "assets/001.jpg" },
      { id: 3, username: "Emily Wagner", profilePicture: "assets/003.jpg" },
      { id: 4, username: "Jonas Becker", profilePicture: "assets/001.jpg" },
    ],
  },
  {
    id: 3,
    profilePicture: "assets/003.jpg",
    username: "Emily Wagner",
    petType: "Bird",
    Friends: [
      { id: 1, username: "Lena Fischer", profilePicture: "assets/001.jpg" },
      { id: 2, username: "Tobias Meier", profilePicture: "assets/002.jpg" },
      { id: 4, username: "Jonas Becker", profilePicture: "assets/001.jpg" },
    ],
  },
  {
    id: 4,
    profilePicture: "assets/001.jpg",
    username: "Jonas Becker",
    petType: "Dog",
    Friends: [
      { id: 1, username: "Lena Fischer", profilePicture: "assets/001.jpg" },
      { id: 2, username: "Tobias Meier", profilePicture: "assets/002.jpg" },
      { id: 3, username: "Emily Wagner", profilePicture: "assets/003.jpg" },
    ],
  },
  {
    id: 5,
    profilePicture: "assets/002.jpg",
    username: "Mila Schulz",
    petType: "Cat",
  },
  {
    id: 6,
    profilePicture: "assets/003.jpg",
    username: "Noah Hoffmann",
    petType: "Dog",
  },
  {
    id: 7,
    profilePicture: "assets/003.jpg",
    username: "Sophie Braun",
    petType: "Dog",
  },
  {
    id: 8,
    profilePicture: "assets/002.jpg",
    username: "Leon Schäfer",
    petType: "Cat",
  },
  {
    id: 9,
    profilePicture: "assets/001.jpg",
    username: "Lara Zimmermann",
    petType: "Dog",
  },
  {
    id: 10,
    profilePicture: "assets/001.jpg",
    username: "Finn Kaiser",
    petType: "Dog",
  },
  {
    id: 11,
    profilePicture: "assets/002.jpg",
    username: "Emma Richter",
    petType: "Dog",
  },
  {
    id: 12,
    profilePicture: "assets/003.jpg",
    username: "Maximilian Wolf",
    petType: "Cat",
  },
  {
    id: 13,
    profilePicture: "assets/001.jpg",
    username: "Hannah Weber",
    petType: "Dog",
  },
  {
    id: 14,
    profilePicture: "assets/002.jpg",
    username: "Paul Zimmer",
    petType: "Cat",
  },
  {
    id: 15,
    profilePicture: "assets/003.jpg",
    username: "Laura Klein",
    petType: "Bird",
  },
  {
    id: 16,
    profilePicture: "assets/001.jpg",
    username: "Tim Hoffmann",
    petType: "Dog",
  },
  {
    id: 17,
    profilePicture: "assets/002.jpg",
    username: "Nina Schwarz",
    petType: "Cat",
  },
  {
    id: 18,
    profilePicture: "assets/003.jpg",
    username: "Jonas Richter",
    petType: "Dog",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/alex-robertson-33LI6oorkrY-unsplash.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/jessica-christian-s33JGIxpBjk-unsplash.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/pierre-lemos-wfOdYsDrxvs-unsplash.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/pierre-lemos-wfOdYsDrxvs-unsplash.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/jessica-christian-s33JGIxpBjk-unsplash.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/alex-robertson-33LI6oorkrY-unsplash.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/jessica-christian-s33JGIxpBjk-unsplash.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/alex-robertson-33LI6oorkrY-unsplash.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/alex-robertson-33LI6oorkrY-unsplash.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/jessica-christian-s33JGIxpBjk-unsplash.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
export const matchRequests = [
  {
    id: 1,
    userId: 1, // Lena Fischer (Dog)
    petType: "Dog",
    location: "Central Park",
    description: "Looking for a pet meet-up!",
    createdAt: "2025-08-06T19:08:02",
  },
  {
    id: 2,
    userId: 4, // Jonas Becker (Dog)
    petType: "Dog",
    location: "Central Park",
    description: "My dog needs new friends.",
    createdAt: "2025-08-06T18:55:00",
  },
  {
    id: 3,
    userId: 6, // Noah Hoffmann (Dog)
    petType: "Dog",
    location: "Dog Park",
    description: "Looking for a walk buddy.",
    createdAt: "2025-08-06T18:30:00",
  },
  {
    id: 4,
    userId: 2, // Tobias Meier (Cat)
    petType: "Cat",
    location: "Main Square",
    description: "Cat lovers meetup this weekend!",
    createdAt: "2025-08-06T17:45:00",
  },
  {
    id: 5,
    userId: 15, // Laura Klein (Bird)
    petType: "Bird",
    location: "Green Garden",
    description: "Bird watching meetup 🐦",
    createdAt: "2025-08-06T17:00:00",
  },
];
